name: ExcellentCrates
main: su.nightexpress.excellentcrates.ExcellentCrates
version: ${version}
api-version: '1.19'
authors: [ NightExpress ]
contributors: [ Nailm ]
description: Fully customizable crates with rewards. Enjoy.
dependencies:
  server:
    NexEngine:
      load: BEFORE
      required: true
      join-classpath: true
    Vault:
      load: OMIT
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: OMIT
      required: false
      join-classpath: true
    DecentHolograms:
      load: OMIT
      required: false
      join-classpath: true
    HolographicDisplays:
      load: OMIT
      required: false
      join-classpath: true
    Citizens:
      load: OMIT
      required: false
      join-classpath: true
