name: ExcellentCrates
main: su.nightexpress.excellentcrates.ExcellentCrates
version: ${version}
api-version: 1.19
authors: [ NightExpress, Nailm ]
description: ${description}
load-before: [ ]
load-after:
  - name: NexEngine
dependencies:
  - name: NexEngine
    required: true
    bootstrap: false
  - name: MewCore
    required: true
    bootstrap: false
  - name: Vault
    required: false
    bootstrap: false
  - name: PlaceholderAPI
    required: false
    bootstrap: false
  - name: DecentHolograms
    required: false
    bootstrap: false
  - name: HolographicDisplays
    required: false
    bootstrap: false
  - name: Citizens
    required: false
    bootstrap: false
