Title: Crate Preview
Size: 36

Reward:
  Hide_Drained_Rewards: false
  Name: '<yellow>%reward_preview_name%'
  Lore:
    Default:
    - '<#cdf34d><b>Chance: <white>%reward_chance%%'
#    - ''
#    - '<#ec7063>Win Limit: <white>%reward_win_limit_amount%'
#    - '<#ec7063>Win Cooldown: <white>%reward_win_limit_cooldown%'
    - ''
    - '%win_limit_amount%'
    - '%win_limit_cooldown%'
    - '%win_limit_drained%'
    - ''
    - '%reward_preview_lore%'
    Win_Limit:
      Amount:
        - '<#ec7063>You can win this reward <white>%user_reward_win_limit_amount_left%</white> more times <gray>(of total <white>%reward_win_limit_amount%</white>)'
      Cooldown:
        - '<#ec7063>You can win this reward again in <white>%user_reward_win_limit_expire_in%'
      Drained:
        - '<#ec7063>You already won this reward, you can not win more.'
  Slots: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26

Content:
  page_next:
    Display:
      default:
        Item:
          Material: 'PLAYER_HEAD'
          Name: '<yellow><b>Next Page'
          Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjgyYWQxYjljYjRkZDIxMjU5YzBkNzVhYTMxNWZmMzg5YzNjZWY3NTJiZTM5NDkzMzgxNjRiYWM4NGE5NmUifX19'
    Slots: 35
    Type: PAGE_NEXT

  page_previous:
    Display:
      default:
        Item:
          Material: 'PLAYER_HEAD'
          Name: '<yellow><b>Previous Page'
          Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzdhZWU5YTc1YmYwZGY3ODk3MTgzMDE1Y2NhMGIyYTdkNzU1YzYzMzg4ZmYwMTc1MmQ1ZjQ0MTlmYzY0NSJ9fX0='
    Slots: 27
    Type: PAGE_PREVIOUS

  exit:
    Display:
      default:
        Item:
          Material: PLAYER_HEAD
          Name: '<white><b>Exit'
          Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTA2ZmJjNzU2MWVhZGNjZjdiYzZkNWE5NmM0NjM1MTRkNzlmZTY0ODlmZTE5OTJkZTQxNjBiYTI3MjA4ZjU1In19fQ=='
    Slots: 31
    Type: CLOSE